# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.160.5+26.3

# Mod Properties
mod_version=0.3.15
maven_group=com.tom5454.toms_trading
archives_base_name=toms_trading_network-fabric-26.3

cloth_config_version=13.0.121
rei_version=20.0.810